org: marutyan21
app: youtube-most-popular
service: news
frameworkVersion: '3'

custom:
  youtubeName: 'youtube-table-${sls:stage}'
  myTableName: my_table

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchWriteItem
            - dynamodb:BatchDeleteItem
            - dynamodb:DescribeStream
            - dynamodb:GetRecords
            - dynamodb:GetShardIterator
            - dynamodb:ListStreams
            - ssm:GetParameter
          Resource: "*"

  environment:
    YOUTUBE_TABLE: ${self:custom.youtubeName}
    MY_TABLE: ${self:custom.myTableName}


functions:
  mostPopular:
    handler: dist/app.handler
    environment:
      YouTube_API: ${ssm:/YouTube_API}
    events:
      - http:
          path: you
          method: get
          cors: true
      - eventBridge:
          schedule: rate(60 minutes)

  streamFunction:
    handler: dist/stream.handler
    environment:
      YouTube_API: ${ssm:/YouTube_API}
    events:
      - stream:
          type: dynamodb
          arn: !GetAtt YouTubeTable.StreamArn
          filterPatterns:
            - eventName: [ INSERT ]



resources:
  Resources:
    YouTubeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: title
            AttributeType: S
        KeySchema:
          - AttributeName: title
            KeyType: HASH
        StreamSpecification:
          StreamViewType: NEW_IMAGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.youtubeName}

    MyTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: my_table
        AttributeDefinitions:
          - AttributeName: videoId
            AttributeType: S
        KeySchema:
          - AttributeName: videoId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST



